// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwFMefxHpK9r__1vHUrWof1dZ0KrCHe4',
    appId: '1:617798219508:web:656b42e922e123cb8bd0a1',
    messagingSenderId: '617798219508',
    projectId: 'svtppm-app',
    authDomain: 'svtppm-app.firebaseapp.com',
    storageBucket: 'svtppm-app.firebasestorage.app',
    measurementId: 'G-7CG119XHL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnMlgzNFLv-hvhmF8fmB1FFQ0tBz1g4yk',
    appId: '1:617798219508:android:55a790443ee35bcb8bd0a1',
    messagingSenderId: '617798219508',
    projectId: 'svtppm-app',
    storageBucket: 'svtppm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtuw-tQtthYLXLeRUaGQy8vFERnFOwrsQ',
    appId: '1:617798219508:ios:86610ec44dd0200e8bd0a1',
    messagingSenderId: '617798219508',
    projectId: 'svtppm-app',
    storageBucket: 'svtppm-app.firebasestorage.app',
    iosBundleId: 'com.example.svtPpm',
  );
}
